### ISSUE TITLE
sr review simple has a long load time

### ISSUE THREAD

**Issue by tomlue** [sysrev/srvc-hello#2]
Even after downloading dependencies, sr review simple takes a long time to load ~ 6 seconds. For user experience speed is usually really important. 

Maybe this is something to fix after https://github.com/sysrev/srvc/issues/8

**Comment by john-shaffer** [comment]
For me it takes a little over 1 second to run these lines (in various files), which seems to account for the vast majority of the run time:

```clj
(require '[babashka.deps :as deps])

(deps/add-deps '{:deps {co.insilica/bb-srvc {:mvn/version "0.4.0"}}})

(require '[srvc.bb :as sb])
```
